### ISSUE TITLE
Why use Canvas is prop instead of nesting Canvas?

### ISSUE THREAD

**Issue by ackvf** [prevwong/craft.js#11]
All examples in documentation use Canvas with this pattern:
_note: the code is invalid and D&D hook is omitted for simplicity_
```
const Container = () => ( 
  <div>
    {children}
  </div>
)
// later
<Canvas is={Container} />
```

Why not use
```
const CanvasContainer = () => (
  <div>
    <Canvas>
      {children}
    </Canvas>
  </div>
)
// later
<CanvasContainer />
```
I think the second one is more explicit (better at fine-tuning the exact position of Canvas) and DRY as it doesn't need that one uses the "<Canvas is" pattern every time they want to use the container.

The difference is that the first needs to be used differently than other components every time it is used, and even in the Toolbox:
```
<button ref={ref => connectors.create(ref, <Canvas is={Container}/>)}>Container</button>
<button ref={ref => connectors.create(ref, <CanvasContainer/>)}> CanvasContainer</button>
```

One reason I would see to not put Canvas in the Container directly is for cases where one wants to use Container without being droppable (i.e. not accepting dragged items). But I already use containers vs special droppable components that are meant to always accept items.

Could you please mention the reasoning behind this in the Basic Tutorial?

I like the second pattern more as every component is used the same way and I can actually move the droppable region within the Container or see where exactly it is. It also doesn't happen that I accidentaly forget to use the Container with <Canvas is.

//edit
Allright, an empty nested Canvas introduces additional html markup (as seen in the image below) which might not be desirable, anyway, this can also be worked around.
_note: the canvas uses blue border, container uses red border._
![image](https://user-images.githubusercontent.com/2313018/72260243-b0b22e80-3612-11ea-80e7-7b619addee24.png)

The workaround
_// edit2 My mistake, this actually doesn't work, the div isn't droppable, though I wonder why._
```
export const CanvasContainer = ({children = null, ...props}) => {
  const { connectors: { connect, drag } } = useNode();
  return (
      <Canvas is={() =>
        <div
          style={{ border: "1px dashed red" }}
          id={id}
          ref={ref => connect(drag(ref))}
          {...props}
        >
          {children}
        </div>
      } />
  )
}

// later
<CanvasContainer />
```
which is equivalent to

```
export const Container = ({children = null, ...props}) => {
  const { connectors: { connect, drag } } = useNode();
  return (
    <div
      style={{ border: "1px dashed red" }}
      id={id}
      ref={ref => connect(drag(ref))}
    >
      {children}
    </div>
  )
}

// later
<Canvas is={Container} />
```

I still prefer the `<CanvasContainer/>`, please let me know if that's wrong idea and understanding of the concept.

### PS
Is there an API for droppable similar to how draggable is made?
I would totally prefer to use
`<div ref=(ref => connect(drop(ref)) />`
instead of wrapping my component in `<Canvas is`

**Comment by prevwong** [comment]
Yeah, both ways are correct and you may be right to choose the 2nd pattern if you find it easier to work with.

Initially, I was actually considering to use a similar solution as you've suggested, but I thought it would make the tutorial a bit more long-winded if I introduced the CanvasContainer component.
For example, when I'm trying to explain the `Related Component` section later, where I've to reuse the same `ContainerSettings` for `Card` and `Container`. And if I added `CanvasContainer`, I would have to do add `ContainerSettings` again (so here there will also be some redundancies). Additionally, I would also need to add `CanvasContainer` to the `resolver`.

I also thought it would be good to show that it is possible to do this:
```jsx
<button ref={ref => connectors.create(ref, <Canvas is={Container}/>)}>Container</button>
```
instead of creating a dedicated CanvasContainer component where the only difference is that it's droppable. 

If we can make the tutorial easier-to-follow, then I'm all for it, but this was my thought process as to why the tutorial has the 2nd pattern.

Btw, thank you for your insightful suggestions 👌🏽 I saw you made another issue, I will look into that, shortly!

**Comment by ackvf** [comment]
Thank you for clarifying that both ways are okay. I have actually discovered a flaw in the third workaround I proposed, but anyway, I was really wondering why the second approach wasn't even mentioned - I started thinking that it was wrong, so thank you.
