### ISSUE TITLE
TS support, also in doc...

### ISSUE THREAD

**Issue by LeulAria** [prevwong/craft.js#198]
i haven't found doc,... on ts with craft.js

**Comment by ankri** [comment]
What is it you want to know? 

If you want to know how to use Craft.js in your TypeScript project, you can just do that, since Craft packages its own types 👍 . There's no need to install types from DefinitelyTyped 🎉
 
If you need Type documentation, you can find that [here](https://craft.js.org/r/docs/api/editor-state)

If you need an example on how to use Craft.js with Typescript, have a look at the [landing example](https://github.com/prevwong/craft.js/tree/develop/packages/examples/landing)

**Comment by LeulAria** [comment]
k tnx, the example is better...
