### ISSUE TITLE
Upgrading to 0.1.0-beta.18 is a breaking change.

### ISSUE THREAD

**Issue by mkrkelj1** [prevwong/craft.js#248]
Upgrading to 0.1.0-beta.18 seems to be a breaking change. Editor throws issues related to the regressions caused by [211](https://github.com/prevwong/craft.js/pull/211). Worse yet, downgrading back down to 0.1.0-beta.16 doesn’t resolve the issue, as now it’s missing a dependency: 

./node_modules/@craftjs/core/node_modules/immer/dist/immer.module.js
Module build failed: Error: ENOENT: no such file or directory

Any help would be appreciated. 

MacOS 11.2
ReactJS @ 16.3
NextJS @ 10.2

**Comment by mkrkelj1** [comment]
Downgrading can be resolved by manually installing the proper _utils_ package. Installing `0.1.0-beta.16` installs the proper _core_ package, but not the correct _utils_ package, even with a fresh install. That said, upgrading to 18 & 19 still throws errors related to Immer.

**Comment by prevwong** [comment]
Hi @mkrkelj1,

That is really strange. Those regressions related to `immer` has since been fixed in #214, and that fix was included in 18 and 19. I was unable to reproduce the error on a fresh CodeSandbox; could you create a CodeSandbox so I can take a look? 

Alternatively, if you could do a fresh install after upgrading to 19 and see if that solves it for you? (`immer` was removed from the core package since we only need it in utils)

**Comment by mkrkelj1** [comment]
I ended up installing and rebuilding everything from scratch and it worked. Not sure what the issue was, though it looks like it was specific to my environment. I'll close this, but thank you for the help and for this great package.
