### ISSUE TITLE
setProps doesn't cascade to child Canvas element like I'd expect

### ISSUE THREAD

**Issue by undiwahn** [prevwong/craft.js#31]
[minimalrepro.zip](https://github.com/prevwong/craft.js/files/4143213/minimalrepro.zip)

**Describe the bug**
I'm trying to create a 'container' component, that is basically a styled div with a canvas inside it.  The goal is for the user so select the container component and be able to modify properties on it using a properties panel.  This works great if the prop changes something on the rendered div.  However, if the prop is passed through to my custom  Canvas, no changes are visible.

**To Reproduce**
1. I've attached a minimal repro of what I'm describing.
2. `yarn` and `yarn start` to execute the application
3. open browser to `localhost:3000`
4. The container is blue with a blue frame; this shows that the prop is settings the styled div (frame color) as well as the custom Canvas (background color)
5. Select the container element. The 'Change Color' button appears.
6. Click the button.

**Expected behavior**
The button sets the 'color' prop to yellow, so I would expect both the frame _and_ the background color to become yellow.

**Actual behavior**
The frame turns yellow, so the prop is being changed on the container.  However the background remains blue, indicating the prop change did not cause the canvas to re-render despite the prop being passed into it.

**Screenshots**
![image](https://user-images.githubusercontent.com/9660126/73598529-75b36480-4507-11ea-96c2-4d9ff28d45c1.png)

**Additional context**

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| craft.js           | 0.1.0-beta.1
| React            | 16.12.0
| TypeScript       | 3.7.2
| Browser          | Firefox
| npm/Yarn         | yarn 1.19.1
| Operating System | windows 10

**Comment by prevwong** [comment]
@undiwahn At the moment, this is an expected behaviour where the `<Canvas />` ignores all prop changes after the initial render. Originally, the reason for this was mainly because of the `children` prop, I found it difficult to justify recreating Nodes when the `children` prop of a Canvas is updated.

For example:
```jsx
<Canvas>
    <h2>Hello</h2>
   {
     visible ? (
        <h3>I'm here now</h3>
     ) : null
   }
</Canvas>
```
Initially, we would only have the h2 element, then maybe our user moves the h2 element out of this Canvas, and drops it somewhere else. At this point, there should be nothing in here. Then, let's say the `visible` state is set to true, ideally we would only want to render the new h3 element, but the problem is in React where our updated `children` prop will now contain both h2 and h3, and there really isn't a way to know that we should not render the h2 because the user just moved it somewhere else.  We could do some diffing, but that would probably take way too much work.

Your use case seems to only be concerned with updating the non-`children` props, which makes sense to me. I probably need some time to think this over, but what I've in mind right now is that we should allow changes made to all props except the `children` prop to pass through. What do you think ?

**Comment by undiwahn** [comment]
Your explanation and proposed solution makes sense to me. Specifically, the only prop I _actually_ need to be propagated is the style prop to be able to apply CSS to the canvas DOM element dynamically.  I agree though, the larger use-cases support passing everything that isn't a `children` prop through.

**Comment by bladepop** [comment]
Hi, we've encountered the exact same issue in our project, is there a suggested work-around for this case?

**Comment by prevwong** [comment]
Hey @undiwahn @bladepop 👋I've created a PR which addresses this issue. It should be incorporated into our next release soon, or you can try it out now in the develop branch!
