### ISSUE TITLE
React Native implementation

### ISSUE THREAD

**Issue by syntheticencounters** [prevwong/craft.js#420]
It appears that read-only support for craft.js in react-native is available from what I've read in the other posts.
I'm having issues getting anything to actually render in react-native though.

The frame content being used is generated on the web using craft.js.
No errors are thrown when rendering the content in native but no content is rendered on the screen.

The content for the frame is pretty basic and is comprised of text and image components.
I've tried supplying raw json content to the frame component as well as using actions to deserialize content for the frame.
Both result in no errors but nothing rendered.

Any help would be appreciated and I can supply code as needed.

**Comment by syntheticencounters** [comment]
Yeah I don't remember what the resolution was but I got it up and running for that project and for a few others.

**Comment by aqos156** [comment]
Do you have any example repo or advice in setting it up? Because currently I am trying to run craft.js in expo on web to edit the layout and then want to try to run it on native to only display the json. But I have little luck with creating the editor within the expo web app, it is quite slow, the d&d indicator is missing and I often get the following error

```
Uncaught TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at de (index.js:1:1)
    at e.value (index.js:1:1)
    at index.js:1:1
    at HTMLDivElement.i (index.js:1:1)
```

The example in docs works like a charm.

**Comment by syntheticencounters** [comment]
I may be wrong but I don't recall having to use the dnd package since the editor should be displaying read-only content. I can't share the code for the projects mentioned earlier unfortunately. I'm happy to take a look at some of your code though if you're able to post it.
