### ISSUE TITLE
Is there anyway to implement remove container element when it's empty?

### ISSUE THREAD

**Issue by geohuz** [prevwong/craft.js#523]
Say if a container has serveral Text usercomponent, I want to delete the container when I delete the last Text from container? Or delete the container when dragging the last Text out from the container?

**Comment by ismajl-ramadani** [comment]
Hey @geohuz, can you please ask this question in the Discussions channel, since this is a more general question, or in the Discord server. And when asking a question can you please clarify more about your struggle, what have you tried so far, and also what exactly you need help with? I'm kindly closing the issue now.

Also please read this
https://developer.mozilla.org/en-US/docs/MDN/Community/Open_source_etiquette#find_out_where_to_ask_questions
