### ISSUE TITLE
Reduce bundle size: Use individual packages like `lodash.identity` instead of complete `lodash`

### ISSUE THREAD

**Issue by chavda-bhavik** [prevwong/craft.js#527]
**Is your feature request related to a problem? Please describe.**
It's hard to see that while rendering a page with craftjs, 1/4 portion contains **lodash** with a `531KB` size.
![image](https://github.com/prevwong/craft.js/assets/50201755/77371426-f08a-46ae-a772-8bbabc4416ce)

On the other side, we're using only a few facilities of `lodash`. 
https://github.com/search?q=repo%3Aprevwong%2Fcraft.js%20lodash&type=code

**Describe the solution you'd like**
Instead of using `lodash` we can use individual packages, like,
```
// instead of using
import flatten from 'lodash/flatten';

// use of this will keep bundle size low
import flatten from 'lodash.flatten'
```

**Additional context**
All the used lodash utilities are available as individual packages. Here is the complete list of utilities needed,
1. `lodash.flatten`
2. `lodash.forin`
3. `lodash.clonedeep`
4. `lodash.clonedeep`
5. `lodash.pickby`
6. `lodash.isequalwith`
7. `lodash.isfunction`
8. `lodash.identity`
9. `lodash.mapvalues`

**Comment by ismajl-ramadani** [comment]
Hey @chavda-bhavik, thanks for opening this issue. There are some issues with the related content already posted to the Craft.js repo, but it seems that they're a little bit outdated.
https://github.com/prevwong/craft.js/pull/470
https://github.com/prevwong/craft.js/pull/256

Would you like to improve, all of these imports and create a PR?

Meanwhile, I'm closing this issue since it's not related to the core functionality of Craft.js.
