### ISSUE TITLE
Possible to overlap components, and move freely around canvas?

### ISSUE THREAD

**Issue by 0xFEEDC0DE** [prevwong/craft.js#83]
This might sound like a strange request, though I am wondering if it is possible to freely move components around the entire container, including overlapping other components. Though I do understand the reason for doing it like this. What I mean is like this project, which is using vue rather than react. 

https://vuegg.now.sh/
https://github.com/vuegg/vuegg 

The reason I ask, is because the designer I am making is more or less a basic desktop mockup editor - looking to have the editor being able to move components around like VS. 

The only other thing is maybe use something like react-canvas with craft.js and create new components for it so they can be drawn on the <canvas>.

**Comment by LeulAria** [comment]
any progress...

**Comment by prevwong** [comment]
This is beyond the scope of the project right now as it's not typically used in most page editors. 

However, I believe you can still get this to work but you won't be benefitting from the drag-n-drop system in Craft - (https://github.com/prevwong/craft.js/issues/121) and @ankri had an example on how to do this too if I remember correctly.

**Comment by TheGrimSilence** [comment]
I'd like an example as well. Especially what you mean by VS being able to move freely?

**Comment by ankri** [comment]
Here is a quick [example](https://codesandbox.io/s/craft-beta-017-position-absolute-dragging-wliwi) of how to achieve absolute positioning. The solution still has some flaws but maybe it can help you take off.

Maybe even share your solution in the "Discussions" tab above so we can publish a better example?

**Comment by TheGrimSilence** [comment]
I see what you mean now. Basically you'd have to understand the underlying node structure first. How things are connected. Basically the way Craft works is you have a JSON tree of components that are named via hashes, and other components which list those hashes as their children. I wouldn't say its immediately the best structure but I've never developed something like this before.

The issue with absolute positioning I think, is labeling the parent/child relationship. The way I'd do it with respect to Craft is set a component as absolute, and another as relative. The relative component can move,  but the absolute cannot with a cursor because of how craft has to manage the component events. So you'd have to programmatically interface with the absolute component and adjust it's positioning independent of the user's cursor. For reference see [Webflow Absolute Positioning](https://university.webflow.com/lesson/pin-a-button-to-the-bottom-of-a-form-using-absolute-position).
Personally I'd add the feature as a hotkey, like holding CTRL + Left Click while dragging to move an absolute component.
