### ISSUE TITLE
mobile interaction

### ISSUE THREAD

**Issue by wuichen** [prevwong/craft.js#91]
**Is your feature request related to a problem? Please describe.**
I would like to use craft.js on mobile. however, it currently doesnt support drag and drop event on mobile

**Describe the solution you'd like**
I'm willing to contribute to this feature. i need someone to point me to where in the repo i should look for to make this happen. 

This is an awesome library! thank you very much for all the work

**Comment by prevwong** [comment]
Hey @wuichen 👋  

Adding mobile support is something that I've been wanting to do for quite some time now but haven't manage to get to it yet, so it would be really awesome if you'd like to help out! 

The main event handlers in Craft are added via the `handlers` method in [packages/core/src/events/EventHandlers.ts](https://github.com/prevwong/craft.js/blob/develop/packages/core/src/events/EventHandlers.ts#L23)

The `handlers` method defines a list of connector names and their respective `init` and `events` properties. 

- `init` is a function that performs some preliminary operation when the connector gets attached to a DOM element. 
  - Each `init` function can return a cleanup function to perform a task when the connector gets removed, which usually happens when the editor gets disabled.
```jsx
// Example: 

drag: {
   init: (el) {
      // Add draggable attribute when the drag connector is attached to the DOM
      el.setAttribute('draggable', 'true');

      // Remove the draggable attribute when the connector is disabled (ie. when the editor is disabled)
      return () => el.setAttribute('draggable', 'false');
   }
}
```

- `events` is a list of DOM events to attach to the element. You should use the included `defineEventListener` util when creating a new event here, it shares the same API as the native `addEventListener` method.

**Comment by wuichen** [comment]
ill put this on my list. thanks for the guidance

**Comment by thyngs** [comment]
How is the progress on mobile support?

**Comment by n8sabes** [comment]
@prevwong Craft.js seems to be well designed as an underlying page layout framework with edibility. Are there any plans to add mobile drag-and-drop? Or, do you know of anybody who has been successful implementing it?

**Comment by ankri** [comment]
There is a PR #154 that's still wip with no responses. Want to take over? :)

**Comment by n8sabes** [comment]
I'm still evaluating Craft.js layout engine vs mine. There are some very nice extensibility features in Craft.js and I especially like the canvas draggable / droppable work whereas mine has runtime application-specific functionality I would need to implement at the JSON level in Craft.js. Both my library and Craft.js require touch + drag-n-drop for mobile so it's a tossup at the moment. Worth noting; iOS Safari is a pain in the orifice with touch+drag related scrolling so this could be a bit more challenging than initially thought (TBD). I need to do some experiments with both, but will consider it.

**Comment by ap0l0** [comment]
any updates on this?

**Comment by vizardkill** [comment]
any updates on this?
